language: node_js
node_js:
  - "lts/*"
install:
  - npm install
  - npm install -g gulp
  - npm install -g gulp-cli
script:
  - gulp build
  - tar zcf material.tar.gz  -C ./dist ./ --exclude=material.tar.gz --exclude=node_modules
deploy:
  provider: releases
  api_key: ${GH_TOKEN}
  file: ./material.tar.gz
  skip_cleanup: true
  on:
    tags: true
